[package]
name = "rusty-cards"
version = "0.1.0"
authors = ["NicolenaStiles <nicolena.stiles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for the GUI
tui = "0.16.0"
termion = "1.5"
